/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.reportes;

import controlador.ConnectionDB;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Arman
 */
public class JPanelGenerarReportes extends javax.swing.JPanel {

    private JPanelReportes padre;
    private ConnectionDB conexion;
    /**
     * Creates new form JPanelGenerarReportes
     */
    public JPanelGenerarReportes(JPanelReportes papa) {
        this.padre = papa;
        this.conexion = new ConnectionDB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelTipoReporte = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabelMes = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox<>();
        jButtonEnviar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jPanelContenedorGraficos = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabelTitulo.setText("Generacion de reportes:");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 250, 30));

        jLabelTipoReporte.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTipoReporte.setText("Tipo de reporte:");
        add(jLabelTipoReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 30));

        jComboBoxTipo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagos recibidos segun tipo de cliente", "Reporte 2", "Reporte 3", "Reporte 4", "Reporte n" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 231, 30));

        jLabelMes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelMes.setText("Mes del reporte:");
        add(jLabelMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 110, 30));

        jComboBoxMes.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBoxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesActionPerformed(evt);
            }
        });
        add(jComboBoxMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 231, 30));

        jButtonEnviar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonEnviar.setText("Generar reporte");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarjButtonEnviarActionPerformed(evt);
            }
        });
        add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 150, 30));

        jButtonAtras.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 150, 30));

        jPanelContenedorGraficos.setBackground(new java.awt.Color(102, 102, 102));
        add(jPanelContenedorGraficos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 770, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jComboBoxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMesActionPerformed

    private void jButtonEnviarjButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarjButtonEnviarActionPerformed
        //Dependiendo del tipo de reporte y el mes:
        String mesEs = this.jComboBoxMes.getSelectedItem().toString();
        String mesEn = "null";
        switch(mesEs){ //Se traduce el mes a ingles para poder hacer la consulta
            case "Enero":
                mesEn = "January";
                break;
            case "Febrero":
                mesEn = "February";
                break;
            case "Marzo":
                mesEn = "March";
                break;
            case "Abril":
                mesEn = "April";
                break;
            case "Junio":
                mesEn = "June";
                break;
            case "Julio":
                mesEn = "July";
                break;
            case "Agosto":
                mesEn = "August";
                break;
            case "Septiembre":
                mesEn = "September";
                break;
            case "Octubre":
                mesEn = "October";
                break;
            case "Noviembre":
                mesEn = "November";
                break;
            case "Diciembre":
                mesEn = "December";
                break;
        }
        String tipoReporte = this.jComboBoxTipo.getSelectedItem().toString();
        switch(tipoReporte){
            case "Pagos recibidos segun tipo de cliente"://Reporte que muestra los ingresos por tipo de cliente del mes seleccionado
                DefaultCategoryDataset datos = new DefaultCategoryDataset();
                datos.setValue(conexion.consultarTotalPagos(mesEn, "natural"), "Dinero total recibido", "Clientes naturales");
                datos.setValue(conexion.consultarTotalPagos(mesEn, "corporativo"), "Dinero total recibido", "Clientes corporativos");
                JFreeChart graficoBarras = ChartFactory.createBarChart3D("Pagos recibidos segun tipo de cliente","Tipos de clientes", "Ingresos",datos, PlotOrientation.VERTICAL, true, true, false);
                ChartPanel panelGrafico = new ChartPanel(graficoBarras);
                this.jPanelContenedorGraficos.setLayout(new java.awt.BorderLayout());
                this.jPanelContenedorGraficos.add(panelGrafico);
                this.jPanelContenedorGraficos.validate();
                break;
        }
    }//GEN-LAST:event_jButtonEnviarjButtonEnviarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        padre.eliminarPanel();
        padre.enableButtons(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonEnviar;
    public javax.swing.JComboBox<String> jComboBoxMes;
    public javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JLabel jLabelTipoReporte;
    public javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelContenedorGraficos;
    // End of variables declaration//GEN-END:variables
}
