package vista.usuarios;

import javax.swing.JPanel;
import vista.menuPrincipal;

/**
 *
 * @author Arman
 */
public class JPanelUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form JPanelUsuarios
     */
    private JPanel panelActual;
    private menuPrincipal menup;
    public JPanelUsuarios(menuPrincipal menu) {
        initComponents();
        panelActual=new JPanel();
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1110, 570));
        menup=menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegistrarUsuario = new javax.swing.JButton();
        jButtonAdmiinistrarUsuarios = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1110, 655));
        setPreferredSize(new java.awt.Dimension(1110, 655));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegistrarUsuario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButtonRegistrarUsuario.setText("Registrar Usuario");
        jButtonRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarUsuarioActionPerformed(evt);
            }
        });
        add(jButtonRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 200, 30));

        jButtonAdmiinistrarUsuarios.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButtonAdmiinistrarUsuarios.setText("Administrar Usuarios");
        jButtonAdmiinistrarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdmiinistrarUsuariosActionPerformed(evt);
            }
        });
        add(jButtonAdmiinistrarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 200, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdmiinistrarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdmiinistrarUsuariosActionPerformed
        // TODO add your handling code here:
        this.eliminarPanel();
        this.pintarPanel(new JPanelAdministrarUsuarios(this));
        menup.refrescarGUI();
        this.enableButtons(false);
        
    }//GEN-LAST:event_jButtonAdmiinistrarUsuariosActionPerformed

    private void jButtonRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
        this.eliminarPanel();
        this.pintarPanel(new JPanelDatosUsuario(this), 290, 120);
        menup.refrescarGUI();
        this.enableButtons(false);
    }//GEN-LAST:event_jButtonRegistrarUsuarioActionPerformed
    
    public void pintarPanel(JPanel panel){
        panelActual=panel;
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1110, 570));
        this.revalidate();
        this.repaint();
    }
    
    public void pintarPanel(JPanel panel, int x, int y){//Sobrecarga que recibe coordenadas para centrar el panel
        panelActual=panel;
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, 1110, 570));
        this.revalidate();
        this.repaint();
    }
    
    public void eliminarPanel(){
        this.remove(panelActual);
        this.revalidate();
        this.repaint();
    }
    
    public void enableButtons(boolean b){
        jButtonAdmiinistrarUsuarios.setEnabled(b);
        jButtonRegistrarUsuario.setEnabled(b);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdmiinistrarUsuarios;
    private javax.swing.JButton jButtonRegistrarUsuario;
    // End of variables declaration//GEN-END:variables
}
