package vista.usuarios;

import controlador.ConnectionDB;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Manuel
 */
public class JPanelDatosUsuario extends javax.swing.JPanel {
    
    private JPanelAdministrarUsuarios padreAdmin;
    private JPanelUsuarios padreUsers;
    private JPanel panelActual;
    private ConnectionDB db;
    private boolean tipoPanel; //true=panelAdmin, false = panelUsuarios.
    /**
     * Creates new form JPanelDatosUsuario
     */
    public JPanelDatosUsuario(JPanelAdministrarUsuarios papa) {
        initComponents();
        panelActual = new JPanel();
        tipoPanel=true;
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 890, 490));
        padreAdmin = papa;
        db = new ConnectionDB();
    }
    
    public JPanelDatosUsuario(JPanelUsuarios papa) {
        initComponents();
        titulo.setText("Registro:");
        panelActual = new JPanel();
        tipoPanel=false;
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 890, 490));
        padreUsers = papa;
        db = new ConnectionDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEnviar2 = new javax.swing.JButton();
        jTextPassword2 = new javax.swing.JTextField();
        jTextUsername2 = new javax.swing.JTextField();
        jTextDireccion2 = new javax.swing.JTextField();
        jTextTelefono2 = new javax.swing.JTextField();
        jTextNombre2 = new javax.swing.JTextField();
        jTextCedula2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEnviar2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonEnviar2.setText("Enviar");
        jButtonEnviar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviar2jButtonEnviarActionPerformed(evt);
            }
        });
        add(jButtonEnviar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jTextPassword2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(jTextPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 272, 230, -1));

        jTextUsername2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(jTextUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 224, 230, -1));

        jTextDireccion2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(jTextDireccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 176, 230, -1));

        jTextTelefono2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextTelefono2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefono2jTextTelefonoActionPerformed(evt);
            }
        });
        add(jTextTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 132, 230, -1));

        jTextNombre2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(jTextNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 90, 230, -1));

        jTextCedula2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextCedula2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedula2jTextCedulaActionPerformed(evt);
            }
        });
        add(jTextCedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 44, 230, -1));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel20.setText("Cedula");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 40, 108, 30));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setText("Nombre");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 86, 108, 30));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel19.setText("Telefono");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 128, 108, 30));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel23.setText("Dirección");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 172, 108, 30));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel21.setText("Nombre de usuario");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 220, 108, 30));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel22.setText("Password");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 268, 108, 30));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel24.setText("Rol");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 316, 108, 30));

        titulo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        titulo.setText("jLabel1");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 120, 30));

        jComboBoxRol.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "gerente", "operador" }));
        jComboBoxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRolActionPerformed(evt);
            }
        });
        add(jComboBoxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 316, 231, -1));

        jButtonCancelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviar2jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviar2jButtonEnviarActionPerformed
        // TODO add your handling code here:
        String cedula = jTextCedula2.getText();
        String nombre = jTextNombre2.getText();
        String telefono = jTextTelefono2.getText();
        String direccion = jTextDireccion2.getText();
        String nombre_usuario = jTextUsername2.getText();
        String passwordd = jTextPassword2.getText();
        
        String rol = jComboBoxRol.getItemAt(jComboBoxRol.getSelectedIndex());
        boolean resultado;
        
        if (tipoPanel) {
            resultado = db.updateUsuario(cedula, nombre, telefono, direccion, nombre_usuario, passwordd, rol);
        
            if (resultado) {
                JOptionPane.showMessageDialog(null, "¡La actualización de los datos del usuario fue exitosa!",
                        "Actualización", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "¡No se realizó ninguna modificación!",
                        "Actualización", JOptionPane.ERROR_MESSAGE);
            }
            padreAdmin.eliminarPanel();
            padreAdmin.enableButtons(true);
        } else {
            resultado = db.registrarUsuarios(cedula, nombre, telefono, direccion, nombre_usuario, passwordd, rol);
            
            if(resultado){
                JOptionPane.showMessageDialog(null, "¡El registro de los datos del usuario fue exitoso!",
                        "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                padreUsers.eliminarPanel();
                padreUsers.enableButtons(true);
            } else {
                JOptionPane.showMessageDialog(null, "¡No se pudo realizar el registro!", 
                        "Registro Incorrecto", JOptionPane.ERROR_MESSAGE);
                padreUsers.eliminarPanel();
                padreUsers.enableButtons(true);
            }
        }
              
    }//GEN-LAST:event_jButtonEnviar2jButtonEnviarActionPerformed

    private void jTextTelefono2jTextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefono2jTextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefono2jTextTelefonoActionPerformed

    private void jTextCedula2jTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedula2jTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedula2jTextCedulaActionPerformed

    private void jComboBoxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRolActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        if(tipoPanel){
            padreAdmin.eliminarPanel();
            padreAdmin.enableButtons(true);
        } else {
            padreUsers.enableButtons(true);
            padreUsers.eliminarPanel();
        }
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEnviar2;
    public javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    public javax.swing.JTextField jTextCedula2;
    public javax.swing.JTextField jTextDireccion2;
    public javax.swing.JTextField jTextNombre2;
    public javax.swing.JTextField jTextPassword2;
    public javax.swing.JTextField jTextTelefono2;
    public javax.swing.JTextField jTextUsername2;
    public javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
