package vista;

import vista.usuarios.Login;
import vista.usuarios.JPanelUsuarios;
import javax.swing.JOptionPane;
import modelo.Usuario;
import controlador.ConnectionDB;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Arman
 */
public class menuPrincipal extends javax.swing.JFrame {
    
    private String rol;
    private String nombreUsuario;
    private String fechaSesion;
    private Usuario usuarioLogueado;
    private ConnectionDB conexion;
    private Login login;
    private JPanel panelActual;
    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal(ConnectionDB conex, Login login) {
        this.conexion = conex;
        this.login = login;
        this.usuarioLogueado = conexion.getUsuarioOnline();
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/vista/img/icono.png")).getImage());
        this.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent arg0) {
                cerrarPrograma();
            }
        });
        this.setVisible(true);
        nombreUsuario = usuarioLogueado.getNombre();
        rol = usuarioLogueado.getRol();
        fechaSesion = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime());
        
        labelUsuario.setText(nombreUsuario);
        labelRol.setText(rol);
        labelFecha.setText(fechaSesion);
        
        this.repaint();
        if(rol.equals("administrador")){
            buttonUsuarios.setEnabled(true);
        } else if(rol.equals("gerente")){
            buttonReportes.setEnabled(true);
        } else if(rol.equals("operador")){
            buttonClientes.setEnabled(true);
            buttonPagos.setEnabled(true);
            buttonFacturacion.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Algo raro ha sucedido");
        }
        this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelRol = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        buttonUsuarios = new javax.swing.JButton();
        buttonReportes = new javax.swing.JButton();
        buttonFacturacion = new javax.swing.JButton();
        buttonClientes = new javax.swing.JButton();
        buttonPagos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buttonTerminarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu principal");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(860, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 90, 40));

        labelUsuario.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labelUsuario.setText("jLabel2");
        getContentPane().add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 200, 40));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("Rol:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 40));

        labelRol.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labelRol.setText("jLabel3");
        getContentPane().add(labelRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 150, 40));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Fecha sesion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 140, 40));

        labelFecha.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labelFecha.setText("jLabel4");
        getContentPane().add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 250, 40));

        buttonUsuarios.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonUsuarios.setText("Usuarios");
        buttonUsuarios.setEnabled(false);
        buttonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 120, 40));

        buttonReportes.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonReportes.setText("Reportes");
        buttonReportes.setEnabled(false);
        buttonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonReportesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 256, 120, 40));

        buttonFacturacion.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonFacturacion.setText("Facturacion");
        buttonFacturacion.setEnabled(false);
        getContentPane().add(buttonFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 372, 120, 40));

        buttonClientes.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonClientes.setText("Clientes");
        buttonClientes.setEnabled(false);
        buttonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClientesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 488, 120, 40));

        buttonPagos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonPagos.setText("Pagos");
        buttonPagos.setEnabled(false);
        buttonPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 604, 120, 40));

        jPanel1.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 220, -1, -1));

        buttonTerminarSesion.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        buttonTerminarSesion.setText("Terminar sesion");
        buttonTerminarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTerminarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTerminarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1061, 0, 220, 40));

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTerminarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTerminarSesionActionPerformed
        terminarSesion();
    }//GEN-LAST:event_buttonTerminarSesionActionPerformed

    private void buttonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonReportesActionPerformed

    private void buttonPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPagosActionPerformed

    private void buttonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClientesActionPerformed
    JOptionPane.showMessageDialog(this, "Boton clientes pulsado");  
    // TODO add your handling code here:
    }//GEN-LAST:event_buttonClientesActionPerformed

    private void buttonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUsuariosActionPerformed
        // TODO add your handling code here:
        this.pintarPanelActual(new JPanelUsuarios(this));
    }//GEN-LAST:event_buttonUsuariosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
    
    public void pintarPanelActual(JPanel panel){
        panelActual=panel;
        this.getContentPane().add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 1110, 650));
        this.revalidate();
        this.repaint();
    }
    
    public void eliminarPanelActual(){
        this.getContentPane().remove(panelActual);
        this.revalidate();
        this.repaint();
    }
    
    public void refrescarGUI(){
            this.revalidate();
            this.repaint();
        }
    
    public void terminarSesion(){
        int opcion = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea terminar la sesión?", "Cerrando sesión...", JOptionPane.YES_NO_OPTION);
        if(opcion==0){
        conexion.updateStatus_login(usuarioLogueado.getCedula(), false);
        login.setVisible(true);
        this.dispose();
        }
    }
    
    public void cerrarPrograma() {
        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que desea cerrar el programa?", "Cerrando programa...", JOptionPane.YES_NO_OPTION);
        if (opcion == 0) {
            conexion.updateStatus_login(usuarioLogueado.getCedula(), false);
            this.dispose();
            System.exit(0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClientes;
    private javax.swing.JButton buttonFacturacion;
    private javax.swing.JButton buttonPagos;
    private javax.swing.JButton buttonReportes;
    private javax.swing.JButton buttonTerminarSesion;
    private javax.swing.JButton buttonUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelRol;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
