/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.pagos;

import controlador.ConnectionDB;
import javax.swing.JPanel;
import vista.menuPrincipal;

/**
 *
 * @author Arman
 */
public class JPanelPagos extends javax.swing.JPanel {

    /**
     * Creates new form JPanelPAgos
     */
    private JPanel panelActual;
    private menuPrincipal menup;
    private ConnectionDB db;
    
    
    public JPanelPagos(menuPrincipal menu, ConnectionDB db) {
        initComponents();
        this.setBackground(new java.awt.Color(218, 234, 255));
        panelActual=new JPanel();
        this.panelActual.setBackground(new java.awt.Color(218, 234, 255));
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1110, 570));
        menup=menu;
        this.db = db;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPagoIndividual = new javax.swing.JButton();
        jButtonPagosBancos = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();

        setBackground(new java.awt.Color(218, 234, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPagoIndividual.setBackground(new java.awt.Color(149, 193, 255));
        jButtonPagoIndividual.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonPagoIndividual.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPagoIndividual.setText("Registrar pago individual");
        jButtonPagoIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagoIndividualActionPerformed(evt);
            }
        });
        add(jButtonPagoIndividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 240, 30));

        jButtonPagosBancos.setBackground(new java.awt.Color(149, 193, 255));
        jButtonPagosBancos.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonPagosBancos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPagosBancos.setText("Cargar pagos bancarios");
        jButtonPagosBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagosBancosActionPerformed(evt);
            }
        });
        add(jButtonPagosBancos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 230, 30));

        jButtonAtras.setBackground(new java.awt.Color(149, 193, 255));
        jButtonAtras.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPagoIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagoIndividualActionPerformed
        // TODO add your handling code here:
        this.eliminarPanel();
        this.pintarPanel(new JPanelRegistrarPagos(this, this.db), 130, 140);        
        menup.refrescarGUI();
        this.enableButtons(false);
    }//GEN-LAST:event_jButtonPagoIndividualActionPerformed

    private void jButtonPagosBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagosBancosActionPerformed
        // TODO add your handling code here:
        /*db.updateValorPagoCuentaM();
        db.updateUltimoPagoCuentaM();
        this.eliminarPanel();
        menup.refrescarGUI();
        this.enableButtons(false);*/
        this.pintarPanel(new JPanelPagosBancos (this, this.db), 250,100);
        menup.refrescarGUI();
        this.refrescarGUI();
        this.enableButtons(false);
    }//GEN-LAST:event_jButtonPagosBancosActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        this.menup.buttonPagos.setEnabled(true);
        this.menup.buttonClientes.setEnabled(true);
        this.menup.buttonFacturacion.setEnabled(true);
        this.menup.eliminarPanelActual();
        this.menup.refrescarGUI();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    public void eliminarPanel(){
        this.remove(panelActual);
        this.revalidate();
        this.repaint();
    }
        
    public void refrescarGUI(){
        menup.refrescarGUI();
    }
    
    public void pintarPanel(JPanel panel){
        panelActual=panel;
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1110, 570));
        this.revalidate();
        this.repaint();
    }
    
    public void enableButtons(boolean b){
        jButtonPagoIndividual.setEnabled(b);
        jButtonPagosBancos.setEnabled(b);  
        jButtonAtras.setEnabled(b);
    }
    
    public void pintarPanel(JPanel panel, int x, int y){//Sobrecarga que recibe coordenadas para centrar el panel
        panelActual=panel;
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, 1110, 570));
        this.revalidate();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonPagoIndividual;
    private javax.swing.JButton jButtonPagosBancos;
    // End of variables declaration//GEN-END:variables
}
