/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.facturacion;

/**
 *
 * @author pc
 */
public class JPanelFacturacion extends javax.swing.JPanel {

    /**
     * Creates new form JPanelFacturacion
     */
    public JPanelFacturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genFacturacionBtn = new javax.swing.JButton();
        enviarFacturacionBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genFacturacionBtn.setText("Generar Facturación");
        genFacturacionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genFacturacionBtnActionPerformed(evt);
            }
        });
        add(genFacturacionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        enviarFacturacionBtn.setText("Enviar Facturación");
        enviarFacturacionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarFacturacionBtnActionPerformed(evt);
            }
        });
        add(enviarFacturacionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void genFacturacionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genFacturacionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genFacturacionBtnActionPerformed

    private void enviarFacturacionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarFacturacionBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enviarFacturacionBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarFacturacionBtn;
    private javax.swing.JButton genFacturacionBtn;
    // End of variables declaration//GEN-END:variables
}
