/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.facturacion;

import controlador.ConnectionDB;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Cliente;
import vista.clientes.JPanelTablaClientes;
import vista.menuPrincipal;

/**
 *
 * @author pc
 */
public class JPanelFacturacion extends javax.swing.JPanel {

    private menuPrincipal menup;
    private JPanelTablaClientes tablaClientes;
    private ConnectionDB db;
    
    /**
     * Creates new form JPanelFacturacion
     */
    public JPanelFacturacion(menuPrincipal main, ConnectionDB db) {
        this.menup = main;
        this.tablaClientes = new JPanelTablaClientes(this);
        this.db = db;
        initComponents();
        mostrarBotonesFacturacion(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generacionFacturacionBtn = new javax.swing.JButton();
        facturacionBtn = new javax.swing.JButton();
        labelFiltrar = new javax.swing.JLabel();
        comboTipoEntrega = new javax.swing.JComboBox<>();
        enviarFacturacionBtn = new javax.swing.JButton();
        enviarATodosBtn = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        genFacturacionBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(218, 234, 255));
        setMinimumSize(new java.awt.Dimension(1256, 680));
        setPreferredSize(new java.awt.Dimension(1256, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generacionFacturacionBtn.setBackground(new java.awt.Color(149, 193, 255));
        generacionFacturacionBtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        generacionFacturacionBtn.setForeground(new java.awt.Color(0, 0, 0));
        generacionFacturacionBtn.setText("Generación de Facturación");
        generacionFacturacionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generacionFacturacionBtnActionPerformed(evt);
            }
        });
        add(generacionFacturacionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        facturacionBtn.setBackground(new java.awt.Color(149, 193, 255));
        facturacionBtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        facturacionBtn.setForeground(new java.awt.Color(0, 0, 0));
        facturacionBtn.setText("Facturación");
        facturacionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturacionBtnActionPerformed(evt);
            }
        });
        add(facturacionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, -1, -1));

        labelFiltrar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        labelFiltrar.setForeground(new java.awt.Color(0, 0, 0));
        labelFiltrar.setText("Filtrar por:");
        labelFiltrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(labelFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 30));

        comboTipoEntrega.setBackground(new java.awt.Color(149, 193, 255));
        comboTipoEntrega.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        comboTipoEntrega.setForeground(new java.awt.Color(0, 0, 0));
        comboTipoEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Email", "De Manera Fisica" }));
        comboTipoEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoEntregaActionPerformed(evt);
            }
        });
        add(comboTipoEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        enviarFacturacionBtn.setBackground(new java.awt.Color(149, 193, 255));
        enviarFacturacionBtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        enviarFacturacionBtn.setForeground(new java.awt.Color(0, 0, 0));
        enviarFacturacionBtn.setText("Enviar Facturacion");
        enviarFacturacionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarFacturacionBtnActionPerformed(evt);
            }
        });
        add(enviarFacturacionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, -1, -1));

        enviarATodosBtn.setBackground(new java.awt.Color(149, 193, 255));
        enviarATodosBtn.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        enviarATodosBtn.setForeground(new java.awt.Color(0, 0, 0));
        enviarATodosBtn.setText("Enviar A Todos");
        enviarATodosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarATodosBtnActionPerformed(evt);
            }
        });
        add(enviarATodosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, -1, -1));

        jButtonAtras.setBackground(new java.awt.Color(149, 193, 255));
        jButtonAtras.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 100, 30));

        genFacturacionBtn.setText("Generar Facturación");
        add(genFacturacionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void generacionFacturacionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generacionFacturacionBtnActionPerformed
        // TODO add your handling code here:

        pintarPanel(tablaClientes);
        mostrarBotonesFacturacion(true);
        this.agregarTodos();
        enviarFacturacionBtn.setEnabled(false); // se inhabilita porque no hay fila seleccionada.
    }//GEN-LAST:event_generacionFacturacionBtnActionPerformed

    private void pintarPanel(JPanel panel) {
        Dimension dimTabla = panel.getPreferredSize();
        add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, dimTabla.width, dimTabla.height));
        this.refrescarGUI();
    }
    
    private void pintarPanel() {
        //Dimension dimTabla = panelActual.getPreferredSize();
        //add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, dimTabla.width, dimTabla.height));
        this.refrescarGUI();
    }
    
    public void agregarTodos() {
        List<Cliente> lista = db.obtenerClientes();
        tablaClientes.agregarTodos(lista);
        this.refrescarGUI();
    }
    
    public void agregarTodosCorreo() {
        List<Cliente> lista = db.obtenerClientesCorreo();
        tablaClientes.agregarTodos(lista);
        this.refrescarGUI();
    }
    
    public void agregarTodosDireccion(){
        List<Cliente> lista = db.obtenerClientesDireccion();
        tablaClientes.agregarTodos(lista);
        this.refrescarGUI();
    }
    
    public void refrescarGUI() {
        this.revalidate();
        this.repaint();
    }
    
    public void enableButtons(Boolean b) {
        this.enviarFacturacionBtn.setEnabled(b);
        this.enviarATodosBtn.setEnabled(b);
    }
    
    private void mostrarBotonesFacturacion(boolean b) {
        this.labelFiltrar.setVisible(b);
        this.comboTipoEntrega.setVisible(b);
        this.enviarFacturacionBtn.setVisible(b);
        this.enviarATodosBtn.setVisible(b);
    }
    
    private void facturacionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturacionBtnActionPerformed
        // TODO add your handling code here:
        pintarPanel(tablaClientes);
        mostrarBotonesFacturacion(true);
        agregarTodosCorreo();
        enviarFacturacionBtn.setEnabled(false); // se inhabilita porque no hay fila seleccionada.
    }//GEN-LAST:event_facturacionBtnActionPerformed

    private void comboTipoEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoEntregaActionPerformed
        // TODO add your handling code here:
        int modoEntrega = comboTipoEntrega.getSelectedIndex(); // 0 para email, 1 para direccion.
        if (modoEntrega == 0) {
            agregarTodosCorreo();
            System.out.println("Entra1");
        } else {
            agregarTodosDireccion();
            System.out.println("Entra2");
        }
    }//GEN-LAST:event_comboTipoEntregaActionPerformed
          

    private void enviarFacturacionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarFacturacionBtnActionPerformed
        // TODO add your handling code here:
        // mostrar mensaje diciendo que se envio la facturacion.
        // pendiente validar que se haya seleccionado una fila de la tabla antes
        int result = JOptionPane.showConfirmDialog(null,"¿Seguro que desea enviar la facturacion al cliente?", "Confirmación",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "¡Se ha enviado la facturacion exitosamente!",
                            "Envio exitoso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_enviarFacturacionBtnActionPerformed

    private void enviarATodosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarATodosBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "¡Se ha enviado la facturacion exitosamente!",
                        "Envio exitoso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_enviarATodosBtnActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        this.menup.buttonPagos.setEnabled(true);
        this.menup.buttonClientes.setEnabled(true);
        this.menup.buttonFacturacion.setEnabled(true);
        this.menup.eliminarPanelActual();
        this.menup.refrescarGUI();
    }//GEN-LAST:event_jButtonAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboTipoEntrega;
    private javax.swing.JButton enviarATodosBtn;
    private javax.swing.JButton enviarFacturacionBtn;
    private javax.swing.JButton facturacionBtn;
    private javax.swing.JButton genFacturacionBtn;
    private javax.swing.JButton generacionFacturacionBtn;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JLabel labelFiltrar;
    // End of variables declaration//GEN-END:variables


}
