/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.clientes;

import controlador.ConnectionDB;
import enums.TipoCliente;
import java.util.List;
import javax.swing.JPanel;
import modelo.Cliente;
import modelo.Linea;

/**
 *
 * @author Arman
 */
public class JPanelAdminLineas extends javax.swing.JPanel {

    private JPanelTablaLineas tabla;
    private JPanelTablaLineas panelTabla;
    private JPanel panelActual;
    private ConnectionDB db;
    private JPanelAdminClientes padre;
    private Cliente cliente;
    /**
     * Creates new form JPanelAdminLineas
     */
    public JPanelAdminLineas(JPanelAdminClientes papa, Cliente cliente) {
        this.padre = papa;
        this.cliente = cliente;
        this.db = new ConnectionDB();
        this.tabla = new JPanelTablaLineas(this, this.cliente);
        initComponents();
        this.pintarPanel(tabla, 0, 0);
        this.validarAgregar();
    }

        public void pintarPanel(JPanelTablaLineas panel, int x, int y){
        this.tabla = panel;
        this.panelTabla = panel;
        add(panelTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, 689, 511));
        this.validarAgregar();
        this.revalidate();
        this.repaint();
    }
  
    public void pintarPanel(JPanel panel, int x, int y){//Sobrecarga que recibe coordenadas para centrar el panel
        panelActual=panel;
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, 1110, 570));
        this.revalidate();
        this.repaint();
    }
    
        public void eliminarPanel(){
        this.remove(panelActual);
        panelActual=null;
        this.revalidate();
        this.repaint();
    }
    
    public void eliminarTabla(){
        this.remove(panelTabla);
        panelTabla=null;
        tabla=null;
        this.revalidate();
        this.repaint();
    }
    
    public void enableButtons(boolean b){
        this.JButtonAgregarLinea.setEnabled(b);
        this.JButtonAtras.setEnabled(b);
        this.JButtonModificarLinea.setEnabled(b);
    }
    
    public void validarAgregar(){//Metodo que determina si se pueden agregar mas lineas
        boolean permiso = true;
        if(this.cliente.getTipo()==TipoCliente.natural){//Si es un cliente natural, se debe verificar que no tenga 3 numeros ya
            List<Linea> lista = db.getLineas(cliente);
            if(lista.size()>=3)permiso = false;//Si ya tiene 3 o ¿mas? lineas no se le da permiso
        }
        if(permiso){
            this.JButtonAgregarLinea.setEnabled(true);
        } else {
            this.JButtonAgregarLinea.setEnabled(false);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JButtonModificarLinea = new javax.swing.JButton();
        JButtonAgregarLinea = new javax.swing.JButton();
        JButtonAtras = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JButtonModificarLinea.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        JButtonModificarLinea.setText("Modificar Linea");
        JButtonModificarLinea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JButtonModificarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonModificarLineaActionPerformed(evt);
            }
        });
        add(JButtonModificarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 170, 30));

        JButtonAgregarLinea.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        JButtonAgregarLinea.setText("Agregar Linea");
        JButtonAgregarLinea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JButtonAgregarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAgregarLineaActionPerformed(evt);
            }
        });
        add(JButtonAgregarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 170, 30));

        JButtonAtras.setFont(new java.awt.Font("Verdana", 1, 15)); // NOI18N
        JButtonAtras.setText("Atras");
        JButtonAtras.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAtrasActionPerformed(evt);
            }
        });
        add(JButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonModificarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonModificarLineaActionPerformed
        this.pintarPanel(new JPanelModificarNumero(this, this.tabla.obtenerLinea(), this.cliente), 50, 50);
        this.eliminarTabla();
        this.enableButtons(false);
    }//GEN-LAST:event_JButtonModificarLineaActionPerformed

    private void JButtonAgregarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAgregarLineaActionPerformed
        // TODO add your handling code here:
        this.pintarPanel(new JPanelAgregarNumero(this, this.cliente), 50, 50);
        this.eliminarTabla();
        this.enableButtons(false);
    }//GEN-LAST:event_JButtonAgregarLineaActionPerformed

    private void JButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAtrasActionPerformed
        // TODO add your handling code here:
        padre.eliminarPanel();
        padre.enableAll(true);
        padre.pintarPanel(new JPanel(), 100, 20);
        padre.enableMRS(false, false, false, false);
    }//GEN-LAST:event_JButtonAtrasActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAgregarLinea;
    private javax.swing.JButton JButtonAtras;
    private javax.swing.JButton JButtonModificarLinea;
    // End of variables declaration//GEN-END:variables
}
