/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.clientes;

import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import vista.facturacion.JPanelFacturacion;

/**
 *
 * @author pc
 */
public class JPanelTablaClientes extends javax.swing.JPanel {

    private JPanel padre;
    
    /**
     * Creates new form JPanelTablaClientes
     * @param dad
     */
    public JPanelTablaClientes(JPanel dad) {
        this.padre = dad;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(218, 234, 255));

        jScrollPane1.setBackground(new java.awt.Color(218, 234, 255));

        tablaClientes.setBackground(new java.awt.Color(218, 234, 255));
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cédula", "Nombre", "Teléfono", "Dirección", "Ciudad", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
        // TODO add your handling code here:
        if (tablaClientes.getSelectedRow() != -1) {
            if (padre.getClass() == JPanelAdminClientes.class) {
                JPanelAdminClientes nuevoPadre =  (JPanelAdminClientes) padre;
                nuevoPadre.enableButtons(true);
            } else {
                JPanelFacturacion nuevoPadre = (JPanelFacturacion) padre;
                nuevoPadre.enableButtons(true);
            }
        }
    }//GEN-LAST:event_tablaClientesMouseClicked

    public void agregarTodos(List<Cliente> lista){
        DefaultTableModel modelo = (DefaultTableModel) tablaClientes.getModel();
        
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(modelo.getRowCount()-1);
        }
        
        for(int i =0; i<lista.size();i++){
            modelo.addRow(new Object[]{
                lista.get(i).getCedula(),
                lista.get(i).getNombre(),
                lista.get(i).getTelefono(),
                lista.get(i).getDireccion(),
                lista.get(i).getCiudad(),
                lista.get(i).getTipo()
            });            
        }
        this.refrescarGUI();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables

    private void refrescarGUI() {
        this.repaint();
        this.revalidate();
    }

    public String obtenerCedulaSeleccionada() {
        int row = tablaClientes.getSelectedRow();
        String cedula = tablaClientes.getValueAt(row, 0).toString();
        return cedula;
    }
}
