/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.clientes;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class JPanelClientesSuspender extends javax.swing.JPanel {

    private JPanelAdminClientes padre;
    /**
     * Creates new form JPanelTablaClientesPlan
     */
    public JPanelClientesSuspender(JPanelAdminClientes papa) {
        this.padre = papa;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientesEstadoPlan = new javax.swing.JTable(){
            public boolean editCellAt(int row, int column, java.util.EventObject e) {
                return false;
            }
        }
        ;
        suspenderTodosBtn = new javax.swing.JButton();

        tablaClientesEstadoPlan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cedula", "Número", "Plan", "Estado Plan", "Último Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientesEstadoPlan.setAlignmentX(0.0F);
        tablaClientesEstadoPlan.setAlignmentY(0.0F);
        tablaClientesEstadoPlan.setPreferredSize(new java.awt.Dimension(890, 510));
        tablaClientesEstadoPlan.getTableHeader().setReorderingAllowed(false);
        tablaClientesEstadoPlan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesEstadoPlanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientesEstadoPlan);

        suspenderTodosBtn.setText("Suspender Todos");
        suspenderTodosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspenderTodosBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(suspenderTodosBtn)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(suspenderTodosBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaClientesEstadoPlanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesEstadoPlanMouseClicked
        if (tablaClientesEstadoPlan.getSelectedRow() != -1) {
            // padre.enableMAD(true);
        }
    }//GEN-LAST:event_tablaClientesEstadoPlanMouseClicked

    private void suspenderTodosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspenderTodosBtnActionPerformed
        List<String> numeros = new ArrayList<>();
        
        for (int i = 0; i<tablaClientesEstadoPlan.getRowCount(); i++)
            numeros.add(this.tablaClientesEstadoPlan.getValueAt(i, 2).toString());
        
        this.padre.suspenderTodos(numeros);
    }//GEN-LAST:event_suspenderTodosBtnActionPerformed

    public void agregarClientesPlan(List<String[]> lista) {
        DefaultTableModel modeloDatos = (DefaultTableModel) tablaClientesEstadoPlan.getModel();
        
        while (modeloDatos.getRowCount() > 0) {
            modeloDatos.removeRow(modeloDatos.getRowCount()-1);
        }
        for (int i = 0; i < lista.size(); i++) {
            String[] row =  lista.get(i);
            Object[] fila = new Object[]{row[0], row[1], row[2], row[3], row[4], row[5]};
            modeloDatos.addRow(fila);
        }
    }
    
    public String obtenerPlan() {
        int row = tablaClientesEstadoPlan.getSelectedRow();
        String plan = tablaClientesEstadoPlan.getValueAt(row, 3).toString();
        return plan;
    }
    
    public String obtenerNumeroSeleccionado() {
        int row = tablaClientesEstadoPlan.getSelectedRow();
        String numero = tablaClientesEstadoPlan.getValueAt(row, 2).toString();
        return numero;
    }
    
    public String obtenerCedulaSeleccionada() {
        int row = tablaClientesEstadoPlan.getSelectedRow();
        String cedula = tablaClientesEstadoPlan.getValueAt(row, 1).toString();
        return cedula;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton suspenderTodosBtn;
    private javax.swing.JTable tablaClientesEstadoPlan;
    // End of variables declaration//GEN-END:variables
}
