/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.clientes;

import controlador.ConnectionDB;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Plan;

/**
 *
 * @author Arman
 */
public class JPanelRegistrarCliente extends javax.swing.JPanel {

    /**
     * Creates new form JPanelDatosClientes
     */
    private JPanelClientes padreAdmin;
    private ConnectionDB conexion;
    private Boolean accion;
    private Boolean tipoCliente;
    public JPanelRegistrarCliente(JPanelClientes papa) {
        this.padreAdmin = papa;
        this.accion = true;
        conexion = new ConnectionDB();
        initComponents();
        this.visiblePanelDerecho(false, false);
        this.rellenarComboBoxDerechos();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSiguiente = new javax.swing.JButton();
        jTextCiudad = new javax.swing.JTextField();
        jTextDireccion = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextCedula = new javax.swing.JTextField();
        jLabelCedula = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelCiudad = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelTituloIzquierdo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButtonAtras = new javax.swing.JButton();
        jLabelTituloDerecho = new javax.swing.JLabel();
        jLabelNumero1 = new javax.swing.JLabel();
        jTextNumero1 = new javax.swing.JTextField();
        jLabelNumero2 = new javax.swing.JLabel();
        jTextNumero2 = new javax.swing.JTextField();
        jLabelNumero3 = new javax.swing.JLabel();
        jTextNumero3 = new javax.swing.JTextField();
        jLabelPlan1 = new javax.swing.JLabel();
        jComboBoxPlan1 = new javax.swing.JComboBox<>();
        jLabelPlan2 = new javax.swing.JLabel();
        jComboBoxPlan2 = new javax.swing.JComboBox<>();
        jLabelPlan3 = new javax.swing.JLabel();
        jComboBoxPlan3 = new javax.swing.JComboBox<>();
        jButtonGenerar1 = new javax.swing.JButton();
        jButtonGenerar2 = new javax.swing.JButton();
        jButtonGenerar3 = new javax.swing.JButton();
        jButtonEnviar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(1110, 600));
        setPreferredSize(new java.awt.Dimension(1110, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSiguiente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonSiguiente.setText("Siguiente");
        jButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSiguientejButtonEnviarActionPerformed(evt);
            }
        });
        add(jButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 100, 30));

        jTextCiudad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(jTextCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 230, 30));

        jTextDireccion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(jTextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 230, 30));

        jTextTelefono.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefonojTextTelefonoActionPerformed(evt);
            }
        });
        add(jTextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 230, 30));

        jTextNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 230, 30));

        jTextCedula.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedulajTextCedulaActionPerformed(evt);
            }
        });
        add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 230, 30));

        jLabelCedula.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCedula.setText("Cedula");
        add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 65, 30));

        jLabelNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNombre.setText("Nombre");
        add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 65, 30));

        jLabelTelefono.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTelefono.setText("Telefono");
        add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 65, 30));

        jLabelDireccion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDireccion.setText("Dirección");
        add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 65, 30));

        jLabelCiudad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCiudad.setText("Ciudad");
        add(jLabelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 65, 30));

        jLabelTipo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTipo.setText("Tipo");
        add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 65, 30));

        jLabelTituloIzquierdo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTituloIzquierdo.setText("Datos basicos del cliente:");
        add(jLabelTituloIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 180, 30));

        jComboBoxTipo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "natural", "corporativo" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 231, 30));

        jButtonAtras.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 500, 100, 30));

        jLabelTituloDerecho.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTituloDerecho.setText("Asignacion de numeros:");
        add(jLabelTituloDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 180, 30));

        jLabelNumero1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNumero1.setText("Numero de telefono 1");
        add(jLabelNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 140, 30));

        jTextNumero1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumero1jTextCedulaActionPerformed(evt);
            }
        });
        add(jTextNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 110, 200, 30));

        jLabelNumero2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNumero2.setText("Numero de telefono 2");
        add(jLabelNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 140, 30));

        jTextNumero2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumero2jTextCedulaActionPerformed(evt);
            }
        });
        add(jTextNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 230, 200, 30));

        jLabelNumero3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNumero3.setText("Numero de telefono 3");
        add(jLabelNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 140, 30));

        jTextNumero3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumero3jTextCedulaActionPerformed(evt);
            }
        });
        add(jTextNumero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 350, 200, 30));

        jLabelPlan1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelPlan1.setText("Plan Pospago");
        add(jLabelPlan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 100, 30));

        jComboBoxPlan1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxPlan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlan1ActionPerformed(evt);
            }
        });
        add(jComboBoxPlan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 170, 315, 30));

        jLabelPlan2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelPlan2.setText("Plan Pospago");
        add(jLabelPlan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 100, 30));

        jComboBoxPlan2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxPlan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlan2ActionPerformed(evt);
            }
        });
        add(jComboBoxPlan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 290, 315, 30));

        jLabelPlan3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelPlan3.setText("Plan Pospago");
        add(jLabelPlan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 100, 30));

        jComboBoxPlan3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxPlan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPlan3ActionPerformed(evt);
            }
        });
        add(jComboBoxPlan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 410, 315, 30));

        jButtonGenerar1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonGenerar1.setText("Generar");
        jButtonGenerar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerar1jButtonEnviarActionPerformed(evt);
            }
        });
        add(jButtonGenerar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 110, 100, 30));

        jButtonGenerar2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonGenerar2.setText("Generar");
        jButtonGenerar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerar2jButtonEnviarActionPerformed(evt);
            }
        });
        add(jButtonGenerar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, 100, 30));

        jButtonGenerar3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonGenerar3.setText("Generar");
        jButtonGenerar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerar3jButtonEnviarActionPerformed(evt);
            }
        });
        add(jButtonGenerar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, 100, 30));

        jButtonEnviar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarjButtonEnviarActionPerformed(evt);
            }
        });
        add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 100, 30));

        jButtonCancelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSiguientejButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSiguientejButtonEnviarActionPerformed
        // TODO add your handling code here:
        //Se muestran los elementos del panel derecho dependiendo del tipo de cliente que se desea registrar:
        tipoCliente = (jComboBoxTipo.getItemAt(jComboBoxTipo.getSelectedIndex())).equals("natural");
        this.visiblePanelDerecho(true, tipoCliente);
        
        //Se inhabilitan los elementos del panel izquierdo:
        this.enablePanelIzquierdo(false);
    }//GEN-LAST:event_jButtonSiguientejButtonEnviarActionPerformed

    private void jTextTelefonojTextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefonojTextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefonojTextTelefonoActionPerformed

    private void jTextCedulajTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedulajTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedulajTextCedulaActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        //Se oculta el panel derecho
        this.visiblePanelDerecho(false, false);
        this.enablePanelIzquierdo(true);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jTextNumero1jTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumero1jTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumero1jTextCedulaActionPerformed

    private void jTextNumero2jTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumero2jTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumero2jTextCedulaActionPerformed

    private void jTextNumero3jTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumero3jTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumero3jTextCedulaActionPerformed

    private void jComboBoxPlan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPlan1ActionPerformed

    private void jComboBoxPlan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPlan2ActionPerformed

    private void jComboBoxPlan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPlan3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPlan3ActionPerformed

    private void jButtonGenerar1jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerar1jButtonEnviarActionPerformed
        // TODO add your handling code here:
        jTextNumero1.setText(this.generarNumero());
    }//GEN-LAST:event_jButtonGenerar1jButtonEnviarActionPerformed

    private void jButtonGenerar2jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerar2jButtonEnviarActionPerformed
        // TODO add your handling code here:
        jTextNumero2.setText(this.generarNumero());
    }//GEN-LAST:event_jButtonGenerar2jButtonEnviarActionPerformed

    private void jButtonGenerar3jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerar3jButtonEnviarActionPerformed
        // TODO add your handling code here:
        jTextNumero3.setText(this.generarNumero());
    }//GEN-LAST:event_jButtonGenerar3jButtonEnviarActionPerformed

    private void jButtonEnviarjButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarjButtonEnviarActionPerformed
        // TODO add your handling code here:
        //Se capturan los datos del cliente para registrarlo
        String cedula = jTextCedula.getText();
        String nombre = jTextNombre.getText();
        String telefono = jTextTelefono.getText();
        String direccion = jTextDireccion.getText();
        String ciudad = jTextCiudad.getText();
        String tipo = jComboBoxTipo.getItemAt(jComboBoxTipo.getSelectedIndex());
        boolean resultadoRegistrarCliente;
        
        if (accion) {//Caso en el que se hace un registro
            resultadoRegistrarCliente = conexion.registrarClientes(cedula, nombre, telefono, direccion, ciudad, tipo);//Se hace la consulta

            if (resultadoRegistrarCliente) {//La consulta es exitosa
                //Una vez se registro el cliente, se le debe crear una cuenta y sus respectivas lineas
                if (tipoCliente){//Si es un cliente natural, es decir, un solo numero
                    String numero = jTextNumero1.getText();
                    int idPlan = jComboBoxPlan1.getSelectedIndex()+1;
                    Boolean resultadoRegistrarLinea = conexion.registrarLinea(numero, idPlan);//Se hace el registro de la linea
                    if (resultadoRegistrarLinea){//El registro de Linea fue exitoso
                        Boolean resultadoRegistrarCuenta = conexion.registrarCuenta(cedula, numero);//Se hace el registro de la cuenta
                        if(resultadoRegistrarCuenta){//El registro de cuenta fue exitoso
                            JOptionPane.showMessageDialog(null, "¡El registro de los datos del cliente fue exitoso!",
                    "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                        } else {//El registro de cuenta fallo
                            //Como no se pudo registrar la cuenta, pero si la linea y el cliente, se deben borrar
                            conexion.eliminarLinea(numero);
                            conexion.eliminarCliente(cedula);
                            JOptionPane.showMessageDialog(null, "¡No se pudo realizar el registro!",
                            "Registro fallido", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {//El registro de Linea fallo
                        //Como no se pudo registrar la Linea, se debe borrar el cliente que se registro
                        conexion.eliminarCliente(cedula);
                        JOptionPane.showMessageDialog(null, "¡No se pudo realizar el registro!",
                        "Registro fallido", JOptionPane.ERROR_MESSAGE);
                    }
                } else {//Si son varios numeros
                    //Basicamente toca hacer lo mismo para los tres distintos numeros, valiendose de las validaciones
                }
            } else {//La consulta falla
                JOptionPane.showMessageDialog(null, "¡No se pudo realizar el registro!",
                    "Registro fallido", JOptionPane.ERROR_MESSAGE);
            }
           padreAdmin.eliminarPanel();
           padreAdmin.enableButtons(true);
        } else {//Caso en el que se hace una actualización
            resultadoRegistrarCliente = conexion.updateCliente(cedula, nombre, telefono, direccion, ciudad, tipo);
            if(resultadoRegistrarCliente){
                JOptionPane.showMessageDialog(null, "¡La actualización de los datos del usuario fue exitosa!",
                    "Actualizacion exitosa", JOptionPane.INFORMATION_MESSAGE);
                //padre.eliminarPanel();
                //padre.enableButtons(true);
            } else {
                JOptionPane.showMessageDialog(null, "¡No se realizó ninguna modificación!",
                    "Actualizacion fallida", JOptionPane.ERROR_MESSAGE);
                //padre.eliminarPanel();
                //padre.enableButtons(true);
            }
        }
    }//GEN-LAST:event_jButtonEnviarjButtonEnviarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        if(accion){//Si es una accion de registro
            padreAdmin.eliminarPanel();
            padreAdmin.enableButtons(true);
        } else {//Si es una accion de modificacion
            //padreUsers.enableButtons(true);
            //padreUsers.eliminarPanel();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void visiblePanelDerecho(Boolean b, Boolean t){//Metodo que muestra u oculta el panel derecho recibe dos booleans, el primero determinar si se debe ocultar o mostrar
                                        //El segundo determina si es un cliente natural o corporativo, siendo true natural.
        if (t){//Caso en el que es natural
            jLabelNumero1.setVisible(b);
            jTextNumero1.setVisible(b);
            jLabelPlan1.setVisible(b);
            jComboBoxPlan1.setVisible(b);
            jButtonGenerar1.setVisible(b);
        } else {//Caso en el que es corporativo
            jLabelNumero1.setVisible(b);
            jTextNumero1.setVisible(b);
            jButtonGenerar1.setVisible(b);
            jLabelPlan1.setVisible(b);
            jComboBoxPlan1.setVisible(b);
            
            jLabelNumero2.setVisible(b);
            jTextNumero2.setVisible(b);
            jButtonGenerar2.setVisible(b);
            jLabelPlan2.setVisible(b);
            jComboBoxPlan2.setVisible(b);
            
            jLabelNumero3.setVisible(b);
            jTextNumero3.setVisible(b);
            jButtonGenerar3.setVisible(b);
            jLabelPlan3.setVisible(b);
            jComboBoxPlan3.setVisible(b);
        }
        //Independientemente de cual sea el caso, se debe aplicar la accion para los botones y el titulo:
        jLabelTituloDerecho.setVisible(b);
        jButtonEnviar.setVisible(b);
        jButtonAtras.setVisible(b);
    }

    private void enablePanelIzquierdo (Boolean b){//Metodo que habilita o inhabilita los elementos del panel izquierdo, dependiento del boolean b que reciba
        
        jTextCedula.setEnabled(b);
        jTextNombre.setEnabled(b);
        jTextTelefono.setEnabled(b);
        jTextCiudad.setEnabled(b);
        jTextDireccion.setEnabled(b);
        jComboBoxTipo.setEnabled(b);
        jButtonSiguiente.setEnabled(b);
        jButtonCancelar.setEnabled(b);
    }
    
    private void rellenarComboBoxDerechos(){//Metodo que hace una consulta a la base de datos para obtener los planes disponibles y lleanos los combobox
        ArrayList<Plan> planes = conexion.getPlanes();
        for(int i = 0; i<planes.size(); i++){
            jComboBoxPlan1.addItem((planes.get(i)).getNombre());
            jComboBoxPlan2.addItem((planes.get(i)).getNombre());
            jComboBoxPlan3.addItem((planes.get(i)).getNombre());
        }
    }
    
    private String generarNumero(){//Metodo que genera un numero que no se encuentre registrado
        Random ran = new Random();
        int segundoDigito = ran.nextInt(3) + 0;
        String numero = "3"+segundoDigito;
        int tercerDigito;
        if(segundoDigito==2){//caso en que el numero es 32XXXXXXXX
            tercerDigito= ran.nextInt(4) + 0;
            numero = numero+tercerDigito;
        } else {//Cualquier otro caso
            tercerDigito= ran.nextInt(10) + 0;
            numero = numero+tercerDigito;
        }
        //Hasta este momento el numero tiene 3 digitos
        int digitoAuxiliar;
        for(int i = 0; i<7; i++){//Se le concatenan numeros del 0 al 9 hsta completar 10 digitos
            digitoAuxiliar = ran.nextInt(10) + 0;
            numero = numero+digitoAuxiliar;
        }
        //En este punto ya se genero un numero aleatorio y aunque es muy dificil que ya se haya registrado, va a ser necesario validarlo luego.
        return numero;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonGenerar1;
    private javax.swing.JButton jButtonGenerar2;
    private javax.swing.JButton jButtonGenerar3;
    private javax.swing.JButton jButtonSiguiente;
    public javax.swing.JComboBox<String> jComboBoxPlan1;
    public javax.swing.JComboBox<String> jComboBoxPlan2;
    public javax.swing.JComboBox<String> jComboBoxPlan3;
    public javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumero1;
    private javax.swing.JLabel jLabelNumero2;
    private javax.swing.JLabel jLabelNumero3;
    private javax.swing.JLabel jLabelPlan1;
    private javax.swing.JLabel jLabelPlan2;
    private javax.swing.JLabel jLabelPlan3;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipo;
    public javax.swing.JLabel jLabelTituloDerecho;
    public javax.swing.JLabel jLabelTituloIzquierdo;
    public javax.swing.JTextField jTextCedula;
    public javax.swing.JTextField jTextCiudad;
    public javax.swing.JTextField jTextDireccion;
    public javax.swing.JTextField jTextNombre;
    public javax.swing.JTextField jTextNumero1;
    public javax.swing.JTextField jTextNumero2;
    public javax.swing.JTextField jTextNumero3;
    public javax.swing.JTextField jTextTelefono;
    // End of variables declaration//GEN-END:variables
}
