/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.clientes;

import controlador.ConnectionDB;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Arman
 */
public class JPanelDatosClientes extends javax.swing.JPanel {

    /**
     * Creates new form JPanelDatosClientes
     */
    private JPanelClientes padreAdmin;
    private ConnectionDB conexion;
    private Boolean accion;
    public JPanelDatosClientes(JPanelClientes papa) {
        initComponents();
        jLabelTitulo.setText("Registro:");
        conexion = new ConnectionDB();
        this.padreAdmin = papa;
        this.accion = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEnviar = new javax.swing.JButton();
        jTextCiudad = new javax.swing.JTextField();
        jTextDireccion = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextCedula = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 450));
        setPreferredSize(new java.awt.Dimension(600, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEnviar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarjButtonEnviarActionPerformed(evt);
            }
        });
        add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 100, 30));

        jTextCiudad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(jTextCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 230, 30));

        jTextDireccion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(jTextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 230, 30));

        jTextTelefono.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefonojTextTelefonoActionPerformed(evt);
            }
        });
        add(jTextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 230, 30));

        jTextNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 230, 30));

        jTextCedula.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedulajTextCedulaActionPerformed(evt);
            }
        });
        add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 230, 30));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel20.setText("Cedula");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 65, 30));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setText("Nombre");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 65, 30));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel19.setText("Telefono");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 65, 30));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel23.setText("Dirección");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 65, 30));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel21.setText("Ciudad");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 65, 30));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel24.setText("Tipo");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 65, 30));

        jLabelTitulo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTitulo.setText("jLabel1");
        add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 120, 30));

        jComboBoxTipo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "natural", "corporativo" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 231, 30));

        jButtonCancelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarjButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarjButtonEnviarActionPerformed
        // TODO add your handling code here:
        String cedula = jTextCedula.getText();
        String nombre = jTextNombre.getText();
        String telefono = jTextTelefono.getText();
        String direccion = jTextDireccion.getText();
        String ciudad = jTextCiudad.getText();
        String tipo = jComboBoxTipo.getItemAt(jComboBoxTipo.getSelectedIndex());
        boolean resultado;

        if (accion) {
            resultado = conexion.registrarClientes(cedula, nombre, telefono, direccion, ciudad, tipo);

            if (resultado) {
                JOptionPane.showMessageDialog(null, "¡El registro de los datos del usuario fue exitoso!",
                    "Actualización", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "¡No se pudo realizar el registro!",
                    "Actualización", JOptionPane.ERROR_MESSAGE);
            }
           padreAdmin.eliminarPanel();
           padreAdmin.enableButtons(true);
        } else {
            resultado = conexion.updateCliente(cedula, nombre, telefono, direccion, ciudad, tipo);
            if(resultado){
                JOptionPane.showMessageDialog(null, "¡La actualización de los datos del usuario fue exitosa!",
                    "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                //padre.eliminarPanel();
                //padre.enableButtons(true);
            } else {
                JOptionPane.showMessageDialog(null, "¡No se realizó ninguna modificación!",
                    "Registro Incorrecto", JOptionPane.ERROR_MESSAGE);
                //padre.eliminarPanel();
                //padre.enableButtons(true);
            }
        }

    }//GEN-LAST:event_jButtonEnviarjButtonEnviarActionPerformed

    private void jTextTelefonojTextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefonojTextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefonojTextTelefonoActionPerformed

    private void jTextCedulajTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedulajTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedulajTextCedulaActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        if(accion){
            padreAdmin.eliminarPanel();
            padreAdmin.enableButtons(true);
        } else {
            //padreUsers.enableButtons(true);
            //padreUsers.eliminarPanel();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEnviar;
    public javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabelTitulo;
    public javax.swing.JTextField jTextCedula;
    public javax.swing.JTextField jTextCiudad;
    public javax.swing.JTextField jTextDireccion;
    public javax.swing.JTextField jTextNombre;
    public javax.swing.JTextField jTextTelefono;
    // End of variables declaration//GEN-END:variables
}
