/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.clientes;

import controlador.ConnectionDB;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.Linea;

/**
 *
 * @author Arman
 */
public class JPanelTablaLineas extends javax.swing.JPanel {

    
    private JPanelTablaLineas tabla;
    private ConnectionDB db;
    private JPanelAdminLineas padre;
    private DefaultTableModel modeloT; 
    private Cliente cliente;
    /**
     * Creates new form JPanelTablaLineas
     */
    public JPanelTablaLineas(JPanelAdminLineas papa, Cliente cliente) {
        this.padre = papa;
        this.cliente = cliente;
        this.db = new ConnectionDB();
        this.modeloT = new DefaultTableModel();
        String [] titulo = new String[]{"Numero telefonico", "Plan"};
        this.modeloT.setColumnIdentifiers(titulo);
        initComponents();
        this.jTableLineas.setModel(modeloT);
        this.agregarLineas();
    }
    
    public void agregarLineas(){ //Metodo que agrega todas las lineas del cliente a la tabla
        List<Linea> lista = db.getLineas(cliente);
        for(int i =0; i<lista.size();i++){
            modeloT.addRow(new Object[]{
                lista.get(i).getNumero(),
                lista.get(i).getPlan()
            });            
        }
        this.revalidate();
        this.repaint();
    }
    
        public Linea obtenerLinea() {//Metodo que obtiene la linea en la que esta parado el usuario
        Linea linea;
        int row = this.jTableLineas.getSelectedRow();
        String numero = this.jTableLineas.getValueAt(row, 0).toString();
        linea = db.getLinea(numero);
        return linea;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLineas = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableLineas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableLineas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 510));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLineas;
    // End of variables declaration//GEN-END:variables
}
