/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.clientes;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class JPanelClientesReactivar extends javax.swing.JPanel {

    /**
     * Creates new form JPanelClientesReactivar
     */
    public JPanelClientesReactivar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientesReactivar = new javax.swing.JTable();

        tablaClientesReactivar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cédula", "Número", "Plan", "Estado Plan", "Último Pago"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaClientesReactivar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void agregarClientesReactivar(List<String[]> lista) {
        DefaultTableModel modeloDatos = (DefaultTableModel) tablaClientesReactivar.getModel();
        
        while (modeloDatos.getRowCount() > 0) {
            modeloDatos.removeRow(modeloDatos.getRowCount()-1);
        }
        for (int i = 0; i < lista.size(); i++) {
            String[] row =  lista.get(i);
            Object[] fila = new Object[]{row[0], row[1], row[2], row[3], row[4], row[5]};
            modeloDatos.addRow(fila);
        }
    }
    
    public String obtenerPlan() {
        int row = tablaClientesReactivar.getSelectedRow();
        String plan = tablaClientesReactivar.getValueAt(row, 3).toString();
        return plan;
    }
    
    public String obtenerNumeroSeleccionado() {
        int row = tablaClientesReactivar.getSelectedRow();
        String numero = tablaClientesReactivar.getValueAt(row, 2).toString();
        return numero;
    }
    
    public String obtenerCedulaSeleccionada() {
        int row = tablaClientesReactivar.getSelectedRow();
        String cedula = tablaClientesReactivar.getValueAt(row, 1).toString();
        return cedula;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientesReactivar;
    // End of variables declaration//GEN-END:variables
}
