/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.clientes;

import controlador.ConnectionDB;
import enums.TipoCliente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Cliente;
import modelo.Cuenta;

/**
 *
 * @author Arman
 */
public class JPanelModificarCliente extends javax.swing.JPanel {

    
    private Cliente clienteActualizar;
    private JPanelAdminClientes padreModificar;
    private ConnectionDB conexion;
    /**
     * Creates new form JPanelModificarCliente
     */
    public JPanelModificarCliente(JPanelAdminClientes papa, Cliente cliente) {
        this.padreModificar = papa;
        this.clienteActualizar = cliente;
        conexion = new ConnectionDB();
        initComponents();
        this.prepararUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloIzquierdo = new javax.swing.JLabel();
        jLabelCedula = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JTextField();
        jLabelCiudad = new javax.swing.JLabel();
        jTextCiudad = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButtonEnviar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(555, 555));
        setPreferredSize(new java.awt.Dimension(555, 555));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTituloIzquierdo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTituloIzquierdo.setText("Datos basicos del cliente:");
        add(jLabelTituloIzquierdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 180, 30));

        jLabelCedula.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCedula.setText("Identificacion");
        add(jLabelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 110, 90, 30));

        jTextCedula.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedulajTextCedulaActionPerformed(evt);
            }
        });
        jTextCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCedulaKeyTyped(evt);
            }
        });
        add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 230, 30));

        jLabelNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelNombre.setText("Nombre");
        add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 65, 30));

        jTextNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });
        add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 230, 30));

        jLabelTelefono.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTelefono.setText("Telefono");
        add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 65, 30));

        jTextTelefono.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefonojTextTelefonoActionPerformed(evt);
            }
        });
        jTextTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTelefonoKeyTyped(evt);
            }
        });
        add(jTextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 230, 30));

        jLabelCiudad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCiudad.setText("Ciudad");
        add(jLabelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 65, 30));

        jTextCiudad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCiudadKeyTyped(evt);
            }
        });
        add(jTextCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 230, 30));

        jLabelDireccion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelDireccion.setText("Dirección");
        add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 65, 30));

        jTextDireccion.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDireccionKeyTyped(evt);
            }
        });
        add(jTextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 230, 30));

        jLabelTipo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelTipo.setText("Tipo");
        add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 65, 30));

        jComboBoxTipo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "natural", "corporativo" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 231, 30));

        jButtonEnviar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarjButtonEnviarActionPerformed(evt);
            }
        });
        add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 100, 30));

        jButtonCancelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCedulajTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedulajTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedulajTextCedulaActionPerformed

    private void jTextCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCedulaKeyTyped
        // TODO add your handling code here:
        if(jTextCedula.getText().length() >= 10) evt.consume(); //Que solo acepte max 10 digitos
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) evt.consume();//Que solo acepte numeros
    }//GEN-LAST:event_jTextCedulaKeyTyped

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        // TODO add your handling code here:
        if(jTextNombre.getText().length() >= 100) evt.consume(); //Que solo acepte max 100 digitos
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;
        boolean espacio = key == 32;
        if (!(minusculas || mayusculas || espacio)) evt.consume();//Que solo acepte letras
    }//GEN-LAST:event_jTextNombreKeyTyped

    private void jTextTelefonojTextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefonojTextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefonojTextTelefonoActionPerformed

    private void jTextTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelefonoKeyTyped
        // TODO add your handling code here:
        if(jTextTelefono.getText().length() >= 10) evt.consume(); //Que solo acepte max 10 digitos
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) evt.consume();//Que solo acepte numeros
    }//GEN-LAST:event_jTextTelefonoKeyTyped

    private void jTextCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCiudadKeyTyped
        // TODO add your handling code here:
        if(jTextCiudad.getText().length() >= 100) evt.consume(); //Que solo acepte max 100 digitos
    }//GEN-LAST:event_jTextCiudadKeyTyped

    private void jTextDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDireccionKeyTyped
        // TODO add your handling code here:
        if(jTextDireccion.getText().length() >= 100) evt.consume(); //Que solo acepte max 100 digitos
    }//GEN-LAST:event_jTextDireccionKeyTyped

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jButtonEnviarjButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarjButtonEnviarActionPerformed
        // TODO add your handling code here:
         //Se capturan los datos del cliente para registrarlo o actualizarlo
        String cedula = jTextCedula.getText();
        String nombre = jTextNombre.getText();
        String telefono = jTextTelefono.getText();
        String direccion = jTextDireccion.getText();
        String ciudad = jTextCiudad.getText();
        if(this.validarActualizarCliente()){//Se hace una validación sobre los campos de datos del usuario
            this.actualizarCliente(cedula, nombre, telefono, direccion, ciudad);
        }
    }//GEN-LAST:event_jButtonEnviarjButtonEnviarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        padreModificar.eliminarPanel();
        padreModificar.enableAll(true);
        padreModificar.pintarPanel(new JPanel(), 100, 20);
        padreModificar.enableMRS(false, false, false, false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private boolean validarActualizarCliente(){
        boolean exito = true;
        
        if(jTextCedula.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "¡Ingrese una cedula valida!",
                            "Validacion incorrecta", JOptionPane.ERROR_MESSAGE);
            exito = false;
        }
        
        if(jTextNombre.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "¡Ingrese un nombre valido!",
                            "Validacion incorrecta", JOptionPane.ERROR_MESSAGE);
            exito = false;
        }
        
        if(jTextTelefono.getText().length()<7){
            JOptionPane.showMessageDialog(null, "¡Ingrese una numero telefonico valido!",
                            "Validacion incorrecta", JOptionPane.ERROR_MESSAGE);
            exito = false;
        }
        
        if(jTextCiudad.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "¡Ingrese una ciudad valida!",
                            "Validacion incorrecta", JOptionPane.ERROR_MESSAGE);
            exito = false;
        }
        
        if(jTextDireccion.getText().isBlank()){
            JOptionPane.showMessageDialog(null, "¡Ingrese una direccion valida!",
                            "Validacion incorrecta", JOptionPane.ERROR_MESSAGE);
            exito = false;
        }
        
        return exito;
    }
    
        private void actualizarCliente(String cedula, String nombre, String telefono, String direccion, String ciudad){
        boolean resultadoActualizarCliente = conexion.updateCliente(cedula, nombre, telefono, direccion, ciudad);//Se hace la consulta
        if(resultadoActualizarCliente){//Si se pudieron actualizar los datos del cliente.
            JOptionPane.showMessageDialog(null, "¡La actualizacion de los datos del cliente fue exitosa!",
                    "Actualizacion exitosa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "¡No se pudo realizar la actualización de los datos del cliente!",
                                "Actualizacion fallida", JOptionPane.ERROR_MESSAGE);
        }
        padreModificar.enableAll(true);
        padreModificar.eliminarPanel();
        padreModificar.pintarPanel(new JPanel(), 100, 20);
        padreModificar.enableMRS(false, false, false, false);
    }
    
    private void prepararUpdate(){//Metodo que trae los datos del cliente a actualizar y llena los campos y los bloquea
        //Se holdean todos los parametros del panel izquierdo
        jTextCedula.setText(clienteActualizar.getCedula());
        jTextCedula.setEnabled(false);
        jTextNombre.setText(clienteActualizar.getNombre());
        jTextTelefono.setText(clienteActualizar.getTelefono());
        jTextCiudad.setText(clienteActualizar.getCiudad());
        jTextDireccion.setText(clienteActualizar.getDireccion());
        int n;
        if(clienteActualizar.getTipo()==TipoCliente.natural){
            n=0;
        } else {
            n=1;
        }
        jComboBoxTipo.setSelectedIndex(n);
        jComboBoxTipo.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEnviar;
    public javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipo;
    public javax.swing.JLabel jLabelTituloIzquierdo;
    public javax.swing.JTextField jTextCedula;
    public javax.swing.JTextField jTextCiudad;
    public javax.swing.JTextField jTextDireccion;
    public javax.swing.JTextField jTextNombre;
    public javax.swing.JTextField jTextTelefono;
    // End of variables declaration//GEN-END:variables
}
