/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.clientes;

import javax.swing.JPanel;
import vista.PruebasM;
import vista.menuPrincipal;

/**
 *
 * @author Manuel
 */
public class JPanelPlanes extends javax.swing.JPanel {
    
    private JPanel panelActual;
    private menuPrincipal menup; // Cambiar

    /**
     * Creates new form JPanelPlanes
     */
    public JPanelPlanes(menuPrincipal prue) {
        initComponents();
        panelActual=new JPanel();
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1110, 570));
        menup=prue;
        System.out.println("Sisa");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCrearPlan = new javax.swing.JButton();
        jButtonAdmiinistrarPlanes = new javax.swing.JButton();

        jPanel1.setMinimumSize(new java.awt.Dimension(1110, 655));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 655));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCrearPlan.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButtonCrearPlan.setText("Crear Plan");
        jButtonCrearPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearPlanActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCrearPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 200, 30));

        jButtonAdmiinistrarPlanes.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButtonAdmiinistrarPlanes.setText("Administrar Planes");
        jButtonAdmiinistrarPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdmiinistrarPlanesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdmiinistrarPlanes, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearPlanActionPerformed
        // TODO add your handling code here:
        //this.eliminarPanel();
        //this.pintarPanel(new JPanelDatosPlanes(this));
        menup.refrescarGUI();
        this.enableButtons(false);
    }//GEN-LAST:event_jButtonCrearPlanActionPerformed

    private void jButtonAdmiinistrarPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdmiinistrarPlanesActionPerformed
        // TODO add your handling code here:
        this.eliminarPanel();
        //this.pintarPanel(new JPanelTablaPlanes(this));
        menup.refrescarGUI();
        this.enableButtons(false);

    }//GEN-LAST:event_jButtonAdmiinistrarPlanesActionPerformed

    public void pintarPanel(JPanel panel){
        panelActual=panel;
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1110, 570));
        this.revalidate();
        this.repaint();
    }
    
    public void eliminarPanel(){
        this.remove(panelActual);
        this.revalidate();
        this.repaint();
    }
    
    public void enableButtons(boolean b){
        jButtonAdmiinistrarPlanes.setEnabled(b);
        jButtonCrearPlan.setEnabled(b);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdmiinistrarPlanes;
    private javax.swing.JButton jButtonCrearPlan;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
