/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.clientes;

import controlador.ConnectionDB;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Planes;
import modelo.Usuario;
import vista.usuarios.JPanelUsuarios;

/**
 *
 * @author Manuel
 */
public class JPanelTablaPlanes extends javax.swing.JPanel {
    
    private JPanelUsuarios padrePlan;
    private JPanelDatosPlanes plan;
    private JPanel panelActual;
    private ConnectionDB db;
    private DefaultTableModel modeloT;  


    /**
     * Creates new form JPanelPlanes
     */
    public JPanelTablaPlanes(JPanelUsuarios papa ) {
        padrePlan=papa;
        db = new ConnectionDB();
        modeloT = new DefaultTableModel();
        String [] titulo = new String[]{"Nombre", "Costo", "Mensajes", "Minutos", "Megas", "Descripción"};
        modeloT.setColumnIdentifiers(titulo);
        initComponents();
        jTablePlanes.setModel(modeloT);
        
        //this.agregarTodos();
    }
    
    
    public void agregarTodos(){
        System.out.println("Hola");

        List<Planes> lista = db.getPlanes();
        
        for(int i =0; i<lista.size();i++){
            modeloT.addRow(new Object[]{
                //lista.get(i).getIdentificador(),
                lista.get(i).getNombre(),
                lista.get(i).getPrecio(),
                lista.get(i).getMensajes(),
                lista.get(i).getMinutos(),
                lista.get(i).getMegas(),
                lista.get(i).getDescripcion(),
            });            
        }
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlanes = new javax.swing.JTable();
        jButtonModificar = new javax.swing.JButton();

        jTablePlanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Plan", "Costo", "Mensajes", "Minutos", "Megas", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePlanes);

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonModificar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        plan = new JPanelDatosPlanes(this);
        Integer identificador = indexTabla();
        Planes datosPlan = db.getPlan(identificador);
        //plan.titulo.setText("Modificar");
        plan.jTextFieldNombrePlan.setText(datosPlan.getNombre());
        plan.jTextFieldMinutos.setText(datosPlan.getMinutos());
        plan.jTextFieldMensajes.setText(datosPlan.getMensajes());
        plan.jTextFieldMegas.setText(datosPlan.getMegas());
        plan.jTextFieldPrecio.setText(datosPlan.getPrecio());
        plan.jTextFieldDescripcion.setText(datosPlan.getDescripcion());
        //this.eliminarPanel();
        padrePlan.eliminarTabla();
        padrePlan.pintarPanel(plan);
        padrePlan.refrescarGUI();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    public void pintarPanel(JPanelDatosPlanes panel){
        plan = panel;
        add(plan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 890, 490));
        this.revalidate();
        this.repaint();
    }
    
    public void eliminarTabla() {
        padrePlan.eliminarTabla();
    }
    
    
    
    public Integer indexTabla() {
        int row = jTablePlanes.getSelectedRow();
        //String cedula = jTablePlanes.getValueAt(row, 0).toString();
        return row+1;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlanes;
    // End of variables declaration//GEN-END:variables
}
