/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.clientes;

import controlador.ConnectionDB;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Planes;
import modelo.Usuario;
import vista.usuarios.JPanelUsuarios;

/**
 *
 * @author Manuel
 */
public class JPanelTablaPlanes extends javax.swing.JPanel {
    
    private JPanelUsuarios padrePlan;
    private JPanelDatosPlanes plan;
    private JPanel panelActual;
    private ConnectionDB db;
    private DefaultTableModel modeloT;  


    /**
     * Creates new form JPanelPlanes
     */
    public JPanelTablaPlanes(JPanelUsuarios papa ) {
        padrePlan=papa;
        db = new ConnectionDB();
        modeloT = new DefaultTableModel();
        String [] titulo = new String[]{"Nombre", "Costo", "Mensajes", "Minutos", "Megas", "Descripción"};
        modeloT.setColumnIdentifiers(titulo);
        initComponents();
        jTablePlanes.setModel(modeloT);
        
    }
    
    
    public void agregarTodos(){
        System.out.println("Hola");

        List<Planes> lista = db.getPlanes();
        
        for(int i =0; i<lista.size();i++){
            modeloT.addRow(new Object[]{
                //lista.get(i).getIdentificador(),
                lista.get(i).getNombre(),
                lista.get(i).getPrecio(),
                lista.get(i).getMensajes(),
                lista.get(i).getMinutos(),
                lista.get(i).getMegas(),
                lista.get(i).getDescripcion(),
            });            
        }
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlanes = new javax.swing.JTable();
        jButtonModificar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(218, 234, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePlanes.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTablePlanes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Plan", "Costo", "Mensajes", "Minutos", "Megas", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePlanes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePlanesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePlanes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 868, -1));

        jButtonModificar.setBackground(new java.awt.Color(149, 193, 255));
        jButtonModificar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModificar.setText("Modificar");
        jButtonModificar.setEnabled(false);
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, -1, 23));

        jButtonCancelar.setBackground(new java.awt.Color(149, 193, 255));
        jButtonCancelar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, 23));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        plan = new JPanelDatosPlanes(this);
        Integer identificador = indexTabla();
        Planes datosPlan = db.getPlan(identificador);
        //plan.titulo.setText("Modificar");
        plan.jTextFieldNombrePlan.setText(datosPlan.getNombre());
        plan.jTextFieldMinutos.setText(datosPlan.getMinutos());
        plan.jTextFieldMensajes.setText(datosPlan.getMensajes());
        plan.jTextFieldMegas.setText(datosPlan.getMegas());
        plan.jTextFieldPrecio.setText(datosPlan.getPrecio());
        plan.jTextFieldDescripcion.setText(datosPlan.getDescripcion());
        //this.eliminarPanel();
        padrePlan.eliminarTablaPlanes();
        padrePlan.pintarPanel(plan, 130, 100);
        padrePlan.refrescarGUI();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        padrePlan.eliminarTablaPlanes();
        padrePlan.enableButtons(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTablePlanesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePlanesMouseClicked
        // TODO add your handling code here:
        if (jTablePlanes.getSelectedRow() != -1) {
            enableMC(true);
        }
    }//GEN-LAST:event_jTablePlanesMouseClicked

    public void pintarPanel(JPanelDatosPlanes panel){
        plan = panel;
        add(plan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 890, 490));
        this.revalidate();
        this.repaint();
    }
    
   
      
    public Integer indexTabla() {
        int row = jTablePlanes.getSelectedRow();
        return row+1;
    }
    
    public void auxUpdateGui() {
        padrePlan.eliminarPanel();
        padrePlan.enableButtons(true);
    }
    
    public void enableMC(boolean b) { 
        jButtonModificar.setEnabled(b);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlanes;
    // End of variables declaration//GEN-END:variables
}
