/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.clientes;

import controlador.ConnectionDB;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import vista.usuarios.JPanelUsuarios;

/**
 *
 * @author Manuel
 */
public class JPanelDatosPlanes extends javax.swing.JPanel {
    
    private JPanelUsuarios padreAdmin;
    private JPanelTablaPlanes padrePlan;
    private JPanel panelActual;
    private ConnectionDB db;
    private boolean tipoPanel; //true=panelAdmin, false = panelUsuarios.

    /**
     * Creates new form JPanelDatosPlanes
     */
    public JPanelDatosPlanes(JPanelUsuarios papa) {
        initComponents();
        panelActual = new JPanel();
        tipoPanel=false;
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 890, 490));
        padreAdmin = papa;
        db = new ConnectionDB();
    }
    
    public JPanelDatosPlanes(JPanelTablaPlanes papa) {
        initComponents();
        panelActual = new JPanel();
        tipoPanel=true;
        this.add(panelActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 890, 490));
        padrePlan = papa;
        db = new ConnectionDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombrePlan = new javax.swing.JLabel();
        jLabelMinutos = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelMegas = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelMensajes = new javax.swing.JLabel();
        jTextFieldNombrePlan = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldMinutos = new javax.swing.JTextField();
        jTextFieldMensajes = new javax.swing.JTextField();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldMegas = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        jLabelNombrePlan.setText("Nombre");

        jLabelMinutos.setText("Minutos");

        jLabelPrecio.setText("Precio");

        jLabelMegas.setText("Megas");

        jLabelDescripcion.setText("Descripción");

        jLabelMensajes.setText("Mensajes");

        jTextFieldNombrePlan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldNombrePlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombrePlanActionPerformed(evt);
            }
        });

        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });

        jTextFieldDescripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescripcionActionPerformed(evt);
            }
        });
        jTextFieldDescripcion.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextFieldDescripcionPropertyChange(evt);
            }
        });

        jButtonEnviar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarjButtonEnviarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarjButtonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombrePlan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNombrePlan, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMegas, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMegas, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCancelar)
                                .addGap(86, 86, 86)
                                .addComponent(jButtonEnviar)))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombrePlan)
                    .addComponent(jTextFieldNombrePlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecio)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMinutos)
                    .addComponent(jTextFieldMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMegas)
                        .addGap(33, 33, 33)
                        .addComponent(jLabelMensajes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldMegas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jTextFieldMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnviar)
                    .addComponent(jButtonCancelar))
                .addGap(24, 24, 24))
        );

        jTextFieldDescripcion.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jTextFieldNombrePlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombrePlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombrePlanActionPerformed

    private void jButtonEnviarjButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarjButtonEnviarActionPerformed
        // TODO add your handling code here:
        String nombre = jTextFieldNombrePlan.getText();
        String descripcion = jTextFieldDescripcion.getText();
        Integer precio = Integer.parseInt(jTextFieldPrecio.getText());
        Integer minutos = Integer.parseInt(jTextFieldMinutos.getText());
        Integer megas = Integer.parseInt(jTextFieldMegas.getText());
        Integer mensajes = Integer.parseInt(jTextFieldMensajes.getText());

        boolean resultado;

        if (tipoPanel) { 
            
            Integer identificador = padrePlan.indexTabla();

            //Corregir
            resultado = db.updatePlan(identificador, nombre, descripcion, precio, minutos, megas, mensajes);

            if (resultado) {
                JOptionPane.showMessageDialog(null, "¡La actualización de los datos del usuario fue exitosa!",
                    "Actualización", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "¡No se realizó ninguna modificación!",
                    "Actualización", JOptionPane.ERROR_MESSAGE);
            }
            padrePlan.auxUpdateGui();
        } else {
            resultado = db.registrarPlanes(nombre, descripcion, precio, minutos, megas, mensajes);

            if(resultado){
                JOptionPane.showMessageDialog(null, "¡El registro de los datos del usuario fue exitoso!",
                    "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
                //padreUsers.enableButtons(true);
            } else {
                JOptionPane.showMessageDialog(null, "¡No se pudo realizar el registro!",
                    "Registro Incorrecto", JOptionPane.ERROR_MESSAGE);
                
            }
            padreAdmin.eliminarPanel();
            padreAdmin.enableButtons(true);
        }

    }//GEN-LAST:event_jButtonEnviarjButtonEnviarActionPerformed

    private void jTextFieldDescripcionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionPropertyChange

    private void jTextFieldDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescripcionActionPerformed

    private void jButtonCancelarjButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarjButtonEnviarActionPerformed
        // TODO add your handling code here:
        padrePlan.auxUpdateGui();
    }//GEN-LAST:event_jButtonCancelarjButtonEnviarActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelMegas;
    private javax.swing.JLabel jLabelMensajes;
    private javax.swing.JLabel jLabelMinutos;
    private javax.swing.JLabel jLabelNombrePlan;
    private javax.swing.JLabel jLabelPrecio;
    public javax.swing.JTextField jTextFieldDescripcion;
    public javax.swing.JTextField jTextFieldMegas;
    public javax.swing.JTextField jTextFieldMensajes;
    public javax.swing.JTextField jTextFieldMinutos;
    public javax.swing.JTextField jTextFieldNombrePlan;
    public javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
