package vista.clientes;

import java.awt.Dimension;

/**
 *
 * @author pc
 */
public class ModuloClientes extends javax.swing.JFrame {
    
    private JPanelTablaClientes tablaClientes;

    /**
     * Creates new form ModuloClientes
     */
    public ModuloClientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        tablaClientes = new JPanelTablaClientes(this);
        //pintarPanel();
    }
    
    public void pintarPanel(){
        panelInicial.remove(tablaClientes);
        Dimension dimension = tablaClientes.getPreferredSize();
        panelInicial.add(tablaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, dimension.width, dimension.height));
        System.out.println("ancho: "+dimension.width+" alto: "+dimension.height);
        tablaClientes.agregarTodos();
        this.refreshGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicial = new javax.swing.JPanel();
        mostrarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mostrarBtn.setText("Mostrar");
        mostrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarBtnActionPerformed(evt);
            }
        });
        panelInicial.add(mostrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, -1, -1));

        getContentPane().add(panelInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarBtnActionPerformed
        // TODO add your handling code here:        
        //this.remove(panelInicial);
        //this.revalidate();
        //this.repaint();
        //panelTabla = new JPanelTablaClientes();
        this.pintarPanel();
        this.refreshGUI();
    }//GEN-LAST:event_mostrarBtnActionPerformed

    public void refreshGUI() {
        panelInicial.repaint();
        panelInicial.revalidate();
        this.repaint();
        this.revalidate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuloClientes().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mostrarBtn;
    private javax.swing.JPanel panelInicial;
    // End of variables declaration//GEN-END:variables
}
